language: java cpp

env:
  - THE_MAKEFILE=Makefile.android
  - THE_MAKEFILE=Makefile.linux

before_install:
  - git submodule update --init --recursive
  
install:
  - export ANDROID_HOME=$(pwd)/android-sdk-linux 
  - bash provision.sh

before_script: 
  
script:
  - make -j -f $THE_MAKEFILE all
